/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#d4e3ff',
        'surface-dim': '#031428',
        'surface-bright': '#2a3a50',
        'on-secondary-fixed': '#001c38',
        'surface': '#031428',
        'surface-container-low': '#0b1c31',
        'surface-container': '#0f2035',
        'surface-container-high': '#1a2b40',
        'surface-container-highest': '#26364c',
        'surface-container-lowest': '#000e22',
        'surface-variant': '#26364c',
        'on-surface-variant': '#bbc9cd',
        'surface-tint': '#2fd9f4',
        'outline': '#859397',
        'outline-variant': '#3c494c',
        'primary': '#8aebff',
        'primary-container': '#22d3ee',
        'primary-fixed-dim': '#2fd9f4',
        'on-primary': '#00363e',
        'on-primary-container': '#005763',
        'secondary': '#a9c9f4',
        'secondary-container': '#28486d',
        'on-secondary': '#0c3255',
        'on-secondary-container': '#98b7e2',
        'tertiary': '#ffd6a7',
        'tertiary-container': '#ffb147',
        'on-tertiary': '#472a00',
        'on-tertiary-container': '#704500',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#d4e3ff',
        'inverse-on-surface': '#213147',
        'inverse-primary': '#006877',
        navy: {
          950: '#0f2035',
          900: '#142840',
          800: '#182f4a',
          700: '#213a58',
          600: '#2a4a6f',
        },
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
      },
      animation: {
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'blink': 'blink 1.5s ease-in-out infinite',
      },
      keyframes: {
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.3' },
        },
      },
    },
  },
  plugins: [],
}
